### ISSUE TITLE
Go Through React Tutorial

### ISSUE THREAD

**Issue by JacobSampson** [AprovanLabs/lotus#2]
## Overview

The 'Highly Strung Tennis Tournament' website is written using React.

Go through the React tutorial: https://react.dev/learn

## Description

Create a list of questions, send them over, and add the answers to the [lotus/docs/learning/react.md](https://github.com/AprovanLabs/lotus/docs/learning/react.md) file

## Acceptance Criteria

- [ ] List of questions asked and answered on React

**Comment by WyattKadelbach** [comment]
I have gone over the React tutorial but the link to the [lotus/docs/learning/react.md](https://github.com/AprovanLabs/lotus/docs/learning/react.md) file says not found.

**Comment by JacobSampson** [comment]
Whoops! The document just contained the same tutorial. Here's the updated link: https://github.com/AprovanLabs/lotus/blob/main/docs/learning/react.md. The 'docs/learning/react.md' file in the 'lotus' repo. If preferred, just send questions via Discord, or we can discuss in our meeting
